apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app-chainalliance
    group: cn.tootoo
  name: app-chainalliance
  namespace: sansancloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-chainalliance
      group: cn.tootoo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-chainalliance
        group: cn.tootoo
    spec:
      containers:
      - name: app-chainalliance
        image: app-sansan-chainalliance:v1.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /manager
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /manager
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
