apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app-manager
    group: cn.tootoo
  name: app-manager
  namespace: sansancloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-manager
      group: cn.tootoo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-manager
        group: cn.tootoo
    spec:
      containers:
      - name: app-manager
        image: app-sansan-java:v1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/importPhone.html?mendianId=0&platformUserId=71120&type=5&platformNo=sansancloud&secretCode=sansan
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/importPhone.html?mendianId=0&platformUserId=71120&type=5&platformNo=sansancloud&secretCode=sansan
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
